services:
  redis-service:
    image: redis:7-alpine
    container_name: rpg-redis
    command: redis-server --requirepass redis_rpg
    networks:
      - rpg-net
    volumes:
      - redis-data:/data
    expose:
      - "6379"
    ports:
      - "6379:6379" 
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "redis_rpg", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend-service:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: rpg-backend
    networks:
      - rpg-net
    depends_on:
      redis-service:
        condition: service_healthy
    environment:
      - GIN_MODE=debug
      - REDIS_ADDR=redis-service:6379
      - REDIS_PASSWORD=redis_rpg
    ports:
      - "8080:8080" # Expõe a porta do backend para o host
    restart: unless-stopped

  frontend-service:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: rpg-frontend
    networks:
      - rpg-net
    depends_on:
      - backend-service
    ports:
      - "3000:80"
    # Boa prática: reiniciar o serviço se ele falhar
    restart: unless-stopped

# 'networks' define a rede virtual privada para nossos contêineres
networks:
  rpg-net:
    driver: bridge

# 'volumes' define os volumes nomeados para persistência de dados
volumes:
  redis-data:
    driver: local