apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: gerenciador-frontend:latest # O nome da imagem que vamos construir
        imagePullPolicy: IfNotPresent # Usa a imagem local
        ports:
        - containerPort: 80 # A porta do Nginx
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  type: NodePort # Expõe a aplicação para fora do cluster
  ports:
  - protocol: TCP
    port: 80         # Porta que o serviço expõe
    targetPort: 80   # Porta no contêiner
    # Esta é a porta que você acessará no seu navegador:
    nodePort: 30000